[[redirects]]
from ="/*"
to = "/index.html"
status = 200




[build]
functions = "functions/"
command = "npm install --prefix functions/sendEmail && npm install --prefix functions/sendSubscribeEmail && npm run build"
